# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitSemver < Formula
  desc "Automatically derive semantic versions from Git tags."
  homepage "https://github.com/mdomke/git-semver"
  version "6.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mdomke/git-semver/releases/download/v6.5.0/git-semver_6.5.0_Darwin_x86_64.tar.gz"
      sha256 "822e2813733dbc3f3dcb8be4b653af657e0093a4eb2093c849a9759e45f87f22"

      def install
        bin.install "git-semver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mdomke/git-semver/releases/download/v6.5.0/git-semver_6.5.0_Darwin_arm64.tar.gz"
      sha256 "1bda5187aff4cc9063d21787c4134b86b57b2321bba0fc58c7473bb008d1ca21"

      def install
        bin.install "git-semver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mdomke/git-semver/releases/download/v6.5.0/git-semver_6.5.0_Linux_x86_64.tar.gz"
      sha256 "6145895f189184323a6d657a70d0b01a525bf4bec020a28b9e93ff13328af63e"

      def install
        bin.install "git-semver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdomke/git-semver/releases/download/v6.5.0/git-semver_6.5.0_Linux_arm64.tar.gz"
      sha256 "73b1d8a00dff9a8eaf3bdf8dcc645eb855a5ff76daffa28411923109ef50c984"

      def install
        bin.install "git-semver"
      end
    end
  end
end
